/** Minimal ABI fragments for ProtectedPayments and ArbiterRegistry. */

const TERMS_TUPLE =
  "(address buyer,address merchant,address token,uint128 amount,address arbiter,uint64 fulfillBy,uint32 protectionWindow,bytes32 orderRef,uint64 deadline)";

export const protectedPaymentsAbi = [
  `function pay(${TERMS_TUPLE} terms, bytes merchantSignature) returns (uint256)`,
  `function hashTerms(${TERMS_TUPLE} terms) view returns (bytes32)`,
  "function markFulfilled(uint256 paymentId, bytes32 evidenceHash)",
  "function confirm(uint256 paymentId)",
  "function finalize(uint256 paymentId)",
  "function cancelUnfulfilled(uint256 paymentId)",
  "function merchantRefund(uint256 paymentId, uint128 amount)",
  "function openDispute(uint256 paymentId, uint8 reason, uint128 requested, bytes32 evidenceHash)",
  "function acceptDispute(uint256 paymentId)",
  "function contest(uint256 paymentId, bytes32 evidenceHash)",
  "function executeDefault(uint256 paymentId)",
  "function proposeSettlement(uint256 paymentId, uint128 refundAmount)",
  "function resolve(uint256 paymentId, uint128 refundAmount, bytes32 rulingHash)",
  "function arbiterTimeout(uint256 paymentId)",
  "function attachVerifiedEvidence(uint256 paymentId, bytes32 batchId, bytes32 leaf, bytes32[] proof, uint256 index)",
  "function depositReserve(address token, uint128 amount)",
  "function withdrawReserve(address token, uint128 amount)",
  "function fundPool(address token, uint128 amount)",
  "function claimPending(uint256 paymentId)",
  "function withdraw(address token)",
  "function credits(address token, address account) view returns (uint256)",
  "function reserves(address merchant, address token) view returns (uint128 free, uint128 locked, uint128 debt)",
  "function poolBalance(address token) view returns (uint256)",
  "function pendingClaims(uint256 paymentId) view returns (uint128)",
  "function protectionEndsAt(uint256 paymentId) view returns (uint64)",
  "function instantCapacity(address merchant, address token) view returns (uint256)",
  "function params() view returns (uint32 minProtectionWindow, uint32 maxProtectionWindow, uint32 merchantResponseWindow, uint32 arbitrationWindow, uint16 maxDisputeRatioBps, uint32 minPaymentsForRatio)",
  "function tokenConfig(address token) view returns (bool enabled, uint16 protocolFeeBps, uint16 protectionFeeBps, uint128 buyerDisputeBond, uint128 arbitrationFee)",
  "function merchantStats(address merchant) view returns (uint32 payments, uint32 disputes, uint32 lost)",
  "function buyerStats(address buyer) view returns (uint32 payments, uint32 disputes, uint32 lost)",
  "function disputeRatioBps(address merchant) view returns (uint256)",
  "function disputeRatioExceeded(address merchant) view returns (bool)",
  "function arbiterRegistry() view returns (address)",
  "function getPayment(uint256 paymentId) view returns ((address buyer,address merchant,address token,address arbiter,uint128 amount,uint128 held,uint128 reserveLocked,uint128 refunded,uint64 createdAt,uint64 fulfillBy,uint64 fulfilledAt,uint32 protectionWindow,uint16 protocolFeeBps,uint16 protectionFeeBps,uint8 status,bool instant,bytes32 orderRef))",
  "function getDispute(uint256 paymentId) view returns ((uint8 stage,uint8 reason,uint8 outcome,bool reassigned,address arbiter,uint64 openedAt,uint64 deadline,uint128 requested,uint128 buyerBond,uint128 merchantFee,uint128 refundAwarded,uint136 buyerProposal,uint136 merchantProposal))",
  "event PaymentCreated(uint256 indexed paymentId, address indexed buyer, address indexed merchant, address token, uint256 amount, address arbiter, bytes32 orderRef, bool instant, uint256 reserveLocked)",
  "event PaymentFulfilled(uint256 indexed paymentId, bytes32 evidenceHash, uint64 protectionEndsAt)",
  "event PaymentCompleted(uint256 indexed paymentId, uint256 merchantNet, uint256 protocolFee, uint256 protectionFee)",
  "event PaymentRefunded(uint256 indexed paymentId, uint256 amount, uint256 totalRefunded, bool full)",
  "event DisputeOpened(uint256 indexed paymentId, uint8 indexed reason, uint256 requested, uint256 bond, bytes32 evidenceHash)",
  "event DisputeContested(uint256 indexed paymentId, address indexed arbiter, uint256 fee, bytes32 evidenceHash)",
  "event DisputeClosed(uint256 indexed paymentId, uint8 indexed outcome, uint256 refundAwarded, bytes32 rulingHash)",
  "event RefundSourced(uint256 indexed paymentId, uint256 fromLocked, uint256 fromFree, uint256 fromPool, uint256 pending)",
] as const;

export const arbiterRegistryAbi = [
  "function isEligible(address arbiter) view returns (bool)",
  "function arbiters(address arbiter) view returns (bool approved, uint128 bond, uint32 openCases, uint32 casesResolved, uint32 casesMissed, uint64 exitRequestedAt, bytes32 metadataHash)",
  "function depositBond(uint128 amount)",
  "function withdrawExcessBond(uint128 amount)",
  "function requestExit()",
  "function completeExit()",
  "function setMetadata(bytes32 metadataHash)",
  "function minBond() view returns (uint128)",
] as const;
